### ISSUE TITLE
only clock showing up. weather and forecast are missing..

### ISSUE THREAD

**Issue by Aeromarine** [wiz78/WeatherClock#5]
thank you for the great little project, been keeping me busy for a week..
however after I finally get it started.. only the clock showed nothing thing else.. did I do something wrong? of course I have edit the config.php with all the APIs, City Codes. And I have been looking deep into the codes.. seems all good.. what's wrong then...?!

https://imgur.com/a/rX4WzO6

**Comment by wiz78** [comment]
see if this helps: https://github.com/wiz78/WeatherClock/issues/4

**Comment by Aeromarine** [comment]
perfect! thank you so much for the great project! teacher me a lot.
